<?php

/**
 * @file
 * Integrates Drupal with Gredi DAM.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\helfi_gredi_image\Service\AssetMetadataHelper;
use Drupal\file\Entity\File;
use \Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_theme().
 */
function media_gredidam_theme($existing, $type, $theme, $path) {
  return [
    'checkboxes__gredidam_assets' => [
      'render element' => 'element',
      'template' => 'checkboxes--gredidam-assets',
    ],
  ];
}

/**
 * Implements hook_cron().
 */
function helfi_gredi_image_cron()
{
  /** @var int $last_run */
  $last_run = \Drupal::state()->get('helfi_gredi_image.last_run', 0);
  /** @var int $request_time */
  $request_time = \Drupal::time()->getRequestTime();
  // If 60 minutes passed since last time.
  if (($request_time - $last_run) > 60 * 60 * 24) {
    /** @var \Drupal\Core\Config\ConfigFactoryInterface $config_factory */
    $config_factory = \Drupal::service('config.factory');
    /** @var \Drupal\Core\Datetime\DateFormatterInterface $date_formatter */
    $date_formatter = \Drupal::service('date.formatter');
    /** @var \Drupal\helfi_gredi_image\Service\GrediDamClient $gradi_dam_client */
    $gradi_dam_client = \Drupal::service('helfi_gredi_image.dam_client');
    /** @var \Drupal\helfi_gredi_image\Service\AssetMetadataHelper $metadata_helper */
    $metadata_helper = new AssetMetadataHelper($config_factory, $date_formatter, $gradi_dam_client);
    $metadata_helper->populateMetadataUpdateQueue();
    \Drupal::state()->set('helfi_gredi_image.last_run', $request_time);
  }
}

/**
 * Implements hook_form_id_alter().
 */
function helfi_gredi_image_form_media_gredi_dam_assets_edit_form_alter(&$form, FormStateInterface $form_state) {
  $form['field_external_id']['widget'][0]['#attributes'] = [
    'readonly' => 'readonly',
    'disabled' => 'disabled',
  ];
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function helfi_gredi_image_form_user_form_alter(&$form, FormStateInterface $form_state) {
  $form['field_gredi_dam_password']['widget'][0]['value']['#type'] = 'password';
}

/**
 * Implements hook_ENTITY_TYPE_delete().
 */
function helfi_gredi_image_media_delete(EntityInterface $entity) {
  // Delete media from public folder when a media is deleted from interface.
  $target_id = $entity->field_media_image->target_id;
  $file = File::load($target_id);
  $file->delete();
}
